### ISSUE TITLE
The webpage at https://zenodo.org/record/3242635 might be temporarily down or it may have moved permanently to a new web address.

### ISSUE THREAD

**Issue by gongshuai0606** [JIMonroe/vae-mc#1]
Hi,there is something wrong with the link,how can I install the deep-boltzmann package?

**Comment by JIMonroe** [comment]
That zenodo web address resolved for me (copying and pasting from your question).  Maybe try it again?

**Comment by gongshuai0606** [comment]
> That zenodo web address resolved for me (copying and pasting from your question). Maybe try it again?

Thanks so much for the reply. Sorry for being late in the answering. After changing the computer, I solved it.
